### PR TITLE
Walker pathing optimizations

### PR DESCRIPTION
**Pull request by dmarszk**

### CODE REVIEW

**Comment by denisdifazio** [comment]
This is beautiful

**Comment by dmarszk** [comment]
I just rebased it on top of master (please use pull --force)
It's ready to be merged.

**Comment by Wisling** [comment]
Oh No! You rebased it?!  But I already made more changes on my end!  :P

**Comment by Wisling** [comment]
Also, I should have tested the teleporting mechanism.  There is certainly a descent way of getting the code to do what you intended, so I'll add that in before merging.  'Cause what you described as the purpose for that code, I think I broke it :S

**Comment by dmarszk** [comment]
Dont worry. Just complete your changes locally, then rebase on top of
master, then push force. That is what dirty WIP branches are for.

W dniu czwartek, 19 maja 2016 Wisling notifications@github.com napisał(a):

**Pull request merged**
