### PR TITLE
Stryku dev

### PR DESCRIPTION
**Pull request by stryku**
Added possibility to drop more than one empty flask at once

### CODE REVIEW

**Comment by stryku** [comment]
Ok so I fixed formatting in my code. I noticed that everywhere in my code there are spaces not tabs but in other code in some places are tabs. I think I wont check whole project and change tabs to spaces so I'll leave it as it is.

**Comment by stryku** [comment]
Forgot change in some files. Now everything should be ok

**Comment by dmarszk** [comment]
Did you use uncrustify? The config file for it is in the root dir of repo. It would fix all indents for you.
There is even more broken indents in last commits.

**Comment by stryku** [comment]
Ok now I used it. I'm working with it for the first time so please check if everything is ok.

**Comment by dmarszk** [comment]
Looks great. You ommited adding "other/flaskMoreThan" to getConfigParamName. I'll fix that, among some other stuff that came out after using Uncrustify.

**Comment by dmarszk** [comment]
Squashed into e9396ea198b754f10f01fb28b9b6c4150dc8513c with minor fixes and merged in 74d7481e16b85818ebe49f0031737f84ece05ca9

**Comment by Wisling** [comment]
Hey Stryku.  Your addition looks great!  I changed the logic to use ">=" instead of ">" and change the variable to dropFlasksAt instead of flaskMoreThan.  It also saves the setting properly :) Nice work.

**Pull request closed without merging**
