### PR TITLE
Memory reading optimizations

### PR DESCRIPTION
**Pull request by dmarszk**
Identified two main bottlenecks:
- dynamic memory operations - in current design TA is performing hundreds or more new/delete calls every second
- ReadProcessMemory calls - they are really heavy

### CODE REVIEW

**Comment by Wisling** [comment]
Oh my, you're tackling this?!  Good on you.  I've just left it as is and allow the pointer creation to be in one thread and the deletion to be in another 'cause changing it is a lot of work :p  I may help you out though as it will be better this way.  If it helps at all, the first byte of name is 0 for an uninitialized CTibiaCharacter.

**Comment by dmarszk** [comment]
Yeah it struck me that profiling have shown about 40% of the CPU time being spend in memory read functions during map research. I'm still figuring out the best way to optimize it.

**Comment by felipetnh** [comment]
This looks nice.
By how much percentage is this going to improve TA? :D

**Comment by dmarszk** [comment]
Well, if it ever gets to an optimal implementation - it should cut CPU usage between 30% and half.

**Comment by felipetnh** [comment]
Wow... That would be awesome! :D

**Comment by dmarszk** [comment]
RFC.
I applied some fixes regarding the aferomentioned issues. I tried to do it as simple as possible.

**Comment by dmarszk** [comment]
Roughly... I believe it will make at least 90% less ReadProcessMemory calls. It's possible that there's a more optimal MEMORY_CACHE_ENTRY_SIZE value. Of course the whole bunch of scanning algorithms are broken by design in this case and could be done better, but it's the simplest way to speed them up.

**Pull request merged**
