### PR TITLE
Mana bar

### PR DESCRIPTION
**Pull request by denisdifazio**
Small refinements I forgot to commit in the last pull

### CODE REVIEW

**Comment by dmarszk** [comment]
Just FYI - there were 2 mem leaks and really nasty compiler optimization bug (please always test stuff in Release aswell ;) )
d6d07184f386bf6857733a5d1c9149c3a6a7f552

**Comment by dmarszk** [comment]
It would appear that there's still some issue with this patch, judging from http://tibiaauto.net/forum/viewtopic.php?f=34&t=1018535&start=15

Did anyone test it on Win7 Home Premium x64? (probably home premium part is not that important)

**Comment by dmarszk** [comment]
Wrong. It messes up OGL and DX5. ;)

**Comment by denisdifazio** [comment]
Sorry for the mess guys. I reversed it using DX8+. I totally forgot about the other engines.

**Comment by dmarszk** [comment]
.text:005811B3                 call    dword ptr [edx+14h]

That should give you some thinking. ;)

**Comment by Wisling** [comment]
Good point.  During the update, I was wondering why it wasn't hard-coded.  How on earth did you find where DirectX draws rectangles for the manabar in the first place?

**Comment by dmarszk** [comment]
I guess pretty straightforward would be memory onaccess breakpoint on some creature hp field.
U would likely end up in battlefield hp + gamescreen hp bars rendering procs.

**Comment by denisdifazio** [comment]
Awesome finding Rebel!

Wisling, I was checking all calls to "printText" function. One of these calls is created in the code region where it prints creatures' name. The code for drawing HP bar is near it.

**Comment by Wisling** [comment]
That's a good and easy way to find it.  No specific knowledge of graphic functions necessary.

**Pull request merged**
